apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-python
  labels:
    app: flask-python
#  namespace: tfg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-python
  template:
    metadata:
      labels:
        app: flask-python
    spec:
      containers:
        - name: flask-python
          #image: registry.eu-gb.bluemix.net/acrego/app-python:0.5
          #image: appy-python:1.0
          image: acrego/app-python:latest
          #command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          imagePullPolicy: Always
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
      # nodeSelector:
      #   tfg: "worker00"
      # imagePullSecrets:
      # - name: regcred
