apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  labels:
    run: web-nginx
    name: web-nginx
    visualize: "true"
#  namespace: tfg      
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
    name: port-worker00
  selector:
    app: nginx
