# apiVersion: v1
# kind: Service
# metadata:
#   name: web-nginx
#   labels:
#     run: web-service
# #  namespace: tfg      
# spec:
#   type: NodePort
#   ports:
#   - port: 8080
#     protocol: TCP
#   selector:
#     app: nginx
apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  labels:
    run: web-service
#  namespace: tfg      
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
    name: port-worker00
  - port: 8080
    nodePort: 30090
    protocol: TCP
    name: port-worker01    
  selector:
    app: nginx
