apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-nginx
  labels:
    app: nginx
#  namespace: tfg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.3-alpine
        #command: [ "/bin/sh", "-c", "ls /usr/share/nginx/html", "ls /etc/nginx" ]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: www-volume
          mountPath: /usr/share/nginx/html
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: www-volume
          configMap:
            name: www-nginx
        - name: config-volume
          configMap:
            name: nginx-conf
      nodeSelector:
        tfg : "worker00"
