apiVersion: v1
kind: Service
metadata:
  name: flask-python
  labels:
    app: flask-python
    name: flask-python
    visualize: "true"
#  namespace: tfg
spec:
  selector:
    app: flask-python
  #type: NodePort
  ports:
   - port: 5000
     targetPort: 5000
     protocol: TCP
